// Pure function: maps a Bench Mode evidence + score snapshot into a
// PrefilledUmiaForm matching the canonical Umia Community Track schema
// (apps/web/lib/umia/umia-venture-apply.schema.json v0.1.0).
//
// Hard rule: never fabricate required-but-missing values. Missing fields
// stay editable so the user must fill them before download.

import type {
  GithubEvidence,
  MultiSourceEvidence,
  ScoreResult,
} from "@upgrade-siren/evidence";

import type {
  FieldOrigin,
  PrefilledField,
  PrefilledOwnerContact,
  PrefilledProject,
  PrefilledProjectLinks,
  PrefilledTeamMember,
  PrefilledUmiaForm,
  UmiaOwnerContact,
  UmiaPreferredContact,
  UmiaProject,
  UmiaProjectLinkOther,
  UmiaProjectLinks,
  UmiaRole,
  UmiaTeam,
  UmiaTeamMember,
  UmiaTractionMetricOther,
  UmiaTractionMetrics,
  UmiaVenturePayload,
  UpgradeSirenReportRef,
} from "./types";

const GITHUB_OWNER_RE = /^[A-Za-z0-9](?:[A-Za-z0-9-]{0,62}[A-Za-z0-9])?$/;

// Mirrors umia-venture-apply.schema.json#/properties/project/properties/links/properties/github_repositories
// items.pattern. Auto-filled URLs must round-trip through Ajv without changes.
const GITHUB_REPO_URL_RE = /^https:\/\/github\.com\/[^/]+\/[^/]+\/?$/;

const REPO_AUTOFILL_CAP = 5;

// Pull canonical-pattern repo URLs out of fetched GitHub evidence so the
// Community Track form's `github_repositories` field doesn't block on
// every subject just because the user hasn't typed at least one URL.
//
// Discipline:
//   - Only mine evidence with kind === 'ok'. Errors and absent stay empty.
//   - Skip archived repos (they don't represent ongoing work).
//   - Skip per-repo failures (fetchStatus !== 'ok') — partial fetches lack
//     the metadata that justifies surfacing the URL.
//   - Sort by pushedAt desc so the most actively maintained repos win the
//     cap.
//   - Cap at REPO_AUTOFILL_CAP — Umia's schema accepts more, but more than
//     a handful is noise on the application form.
function repoUrlsFromGithubEvidence(github: GithubEvidence): string[] {
  if (github.kind !== "ok") return [];
  const candidates = github.value.repos.filter(
    (r) => r.fetchStatus === "ok" && !r.archived,
  );
  candidates.sort((a, b) => {
    const aTime = a.pushedAt ? Date.parse(a.pushedAt) : 0;
    const bTime = b.pushedAt ? Date.parse(b.pushedAt) : 0;
    return bTime - aTime;
  });
  const urls: string[] = [];
  for (const repo of candidates) {
    if (urls.length >= REPO_AUTOFILL_CAP) break;
    const url = `https://github.com/${repo.fullName}`;
    if (GITHUB_REPO_URL_RE.test(url)) urls.push(url);
  }
  return urls;
}

function field<T>(
  value: T,
  origin: FieldOrigin,
  sourceLabel: string | null,
): PrefilledField<T> {
  const locked = origin === "ens" || origin === "report" || origin === "manifest";
  return { value, origin, sourceLabel, locked };
}

function emptyField<T>(empty: T): PrefilledField<T> {
  return field(empty, "user", null);
}

function defaultField<T>(value: T): PrefilledField<T> {
  return field(value, "default", null);
}

function readEnsText(
  evidence: MultiSourceEvidence,
  key: string,
): string | null {
  const texts = evidence.subject.inferredTexts;
  if (!texts) return null;
  const v = texts[key];
  if (typeof v !== "string") return null;
  const trimmed = v.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function ensSourceLabel(key: string): string {
  return `from ENS · ${key}`;
}

function githubOwnerUrl(owner: string): string {
  return `https://github.com/${owner}`;
}

// Build a deterministic seed report-ref from evidence + score, when no
// uploaded report UID is supplied by the caller.
function buildReportRef(
  evidence: MultiSourceEvidence,
  score: ScoreResult | null,
  override: Partial<UpgradeSirenReportRef> | null,
): UpgradeSirenReportRef {
  const subjectEns = evidence.subject.name;
  const ref: UpgradeSirenReportRef = {
    subject_ens: subjectEns,
    url: `https://upgrade-siren.vercel.app/b/${encodeURIComponent(subjectEns)}`,
    ...(score !== null
      ? {
          score_100: score.score_100,
          tier: score.tier,
        }
      : {}),
    ...(override ?? {}),
  };
  return ref;
}

// Materialise the report ref into a single submission_notes string the
// canonical Umia schema can carry. Keep it human-readable so a future
// Umia adapter can extract the values with a regex.
function reportRefToNotes(ref: UpgradeSirenReportRef): string {
  const lines: string[] = [
    "App-owned export payload generated by Upgrade Siren (https://upgrade-siren.vercel.app).",
    "Do not auto-submit until a public Umia adapter is available.",
    "Upgrade Siren report reference:",
  ];
  if (ref.subject_ens) lines.push(`  subject_ens: ${ref.subject_ens}`);
  if (ref.uid) lines.push(`  uid: ${ref.uid}`);
  if (ref.hash) lines.push(`  hash: ${ref.hash}`);
  if (ref.url) lines.push(`  url: ${ref.url}`);
  if (ref.score_100 !== undefined) lines.push(`  score_100: ${ref.score_100}`);
  if (ref.tier) lines.push(`  tier: ${ref.tier}`);
  if (ref.computed_at_iso) lines.push(`  computed_at_iso: ${ref.computed_at_iso}`);
  return lines.join("\n");
}

export interface BuildPrefilledFormOptions {
  readonly evidence: MultiSourceEvidence;
  readonly score: ScoreResult | null;
  readonly reportRef?: Partial<UpgradeSirenReportRef> | null;
}

export function buildPrefilledForm(
  options: BuildPrefilledFormOptions,
): PrefilledUmiaForm {
  const { evidence, score, reportRef } = options;
  const subject = evidence.subject;
  const ensName = subject.name;

  // ─── ENS text record reads ───
  const description = readEnsText(evidence, "description");
  const websiteUrl = readEnsText(evidence, "url");
  const githubOwner = readEnsText(evidence, "com.github");
  const twitterRaw =
    readEnsText(evidence, "com.twitter") ?? readEnsText(evidence, "X");
  const telegramRaw = readEnsText(evidence, "org.telegram");
  const discordRaw = readEnsText(evidence, "com.discord");
  const linkedinRaw = readEnsText(evidence, "com.linkedin");
  const farcasterRaw = readEnsText(evidence, "xyz.farcaster");
  const lensRaw = readEnsText(evidence, "org.lens");

  const validGithubOwner =
    githubOwner && GITHUB_OWNER_RE.test(githubOwner) ? githubOwner : null;

  // ─── owner_contacts (canonical schema is an ARRAY of contact objects) ───
  // We seed exactly one contact entry. Name is editable (not derivable
  // from ENS reliably — ENS name is not a person name). Contact channels
  // come from ENS where available and render as locked.
  const seededContact: PrefilledOwnerContact = {
    name: emptyField<string>(""),
    role: defaultField<UmiaRole>("Founder"),
    email: emptyField<string>(""),
    telegram: telegramRaw
      ? field<string>(telegramRaw, "ens", ensSourceLabel("org.telegram"))
      : emptyField<string>(""),
    twitter: twitterRaw
      ? field<string>(
          twitterRaw,
          "ens",
          readEnsText(evidence, "com.twitter") !== null
            ? ensSourceLabel("com.twitter")
            : ensSourceLabel("X"),
        )
      : emptyField<string>(""),
    discord: discordRaw
      ? field<string>(discordRaw, "ens", ensSourceLabel("com.discord"))
      : emptyField<string>(""),
    phone: emptyField<string>(""),
    wallet_address: subject.primaryAddress
      ? field<string>(
          subject.primaryAddress,
          "report",
          "from report · primary address",
        )
      : emptyField<string>(""),
    preferred_contact: defaultField<UmiaPreferredContact>(
      telegramRaw ? "telegram" : twitterRaw ? "twitter" : "email",
    ),
  };

  // ─── team.members[0] (canonical schema requires name + role) ───
  // Both name and role default to editable: ENS name is not a real
  // person name, and role is a UI choice. Handle, github, wallet
  // surface from ENS / report when present.
  const seededMember: PrefilledTeamMember = {
    name: emptyField<string>(""),
    handle: field<string>(ensName, "ens", ensSourceLabel("name")),
    role: defaultField<UmiaRole>("Founder"),
    wallet_address: subject.primaryAddress
      ? field<string>(
          subject.primaryAddress,
          "report",
          "from report · primary address",
        )
      : emptyField<string>(""),
    github: validGithubOwner
      ? field<string>(validGithubOwner, "ens", ensSourceLabel("com.github"))
      : emptyField<string>(""),
    twitter: twitterRaw
      ? field<string>(twitterRaw, "ens", ensSourceLabel("com.twitter"))
      : emptyField<string>(""),
    bio: emptyField<string>(""),
  };

  // ─── project.links ───
  // Schema requires github_repositories items match
  //   ^https://github\.com/[^/]+/[^/]+/?$
  // i.e. specific repos (owner/name), NOT org/user URLs. When the Bench
  // pipeline successfully fetched the GitHub source, we mine top
  // pushedAt-desc non-archived repos (capped) so a typical subject's
  // form validates without manual URL entry. Subjects with no GitHub
  // evidence still leave it editable for user entry.
  const githubRepoUrls = repoUrlsFromGithubEvidence(evidence.github);
  const otherLinks: UmiaProjectLinkOther[] = [];
  if (validGithubOwner) {
    // Park the org URL inside `links.other` so the user can see we
    // detected a GitHub presence even though it doesn't satisfy the
    // repo-URL pattern.
    otherLinks.push({
      label: "GitHub user/org (auto-detected)",
      url: githubOwnerUrl(validGithubOwner),
    });
  }
  if (linkedinRaw) otherLinks.push({ label: "LinkedIn", url: normaliseLinkedIn(linkedinRaw) });
  if (farcasterRaw) otherLinks.push({ label: "Farcaster", url: normaliseFarcaster(farcasterRaw) });
  if (lensRaw) otherLinks.push({ label: "Lens", url: normaliseLens(lensRaw) });

  const links: PrefilledProjectLinks = {
    website: websiteUrl
      ? field<string>(websiteUrl, "ens", ensSourceLabel("url"))
      : emptyField<string>(""),
    github_repositories:
      githubRepoUrls.length > 0
        ? field<ReadonlyArray<string>>(
            githubRepoUrls,
            "report",
            `from GitHub · top ${githubRepoUrls.length} repo${
              githubRepoUrls.length === 1 ? "" : "s"
            } by recent push`,
          )
        : emptyField<ReadonlyArray<string>>(githubRepoUrls),
    github_organization: validGithubOwner
      ? field<string>(
          githubOwnerUrl(validGithubOwner),
          "ens",
          ensSourceLabel("com.github"),
        )
      : emptyField<string>(""),
    docs: emptyField<string>(""),
    demo: emptyField<string>(""),
    twitter: twitterRaw
      ? field<string>(normaliseTwitter(twitterRaw), "ens", ensSourceLabel("com.twitter"))
      : emptyField<string>(""),
    telegram: telegramRaw
      ? field<string>(normaliseTelegram(telegramRaw), "ens", ensSourceLabel("org.telegram"))
      : emptyField<string>(""),
    discord: discordRaw
      ? field<string>(normaliseDiscord(discordRaw), "ens", ensSourceLabel("com.discord"))
      : emptyField<string>(""),
    other: otherLinks.length > 0
      ? field<ReadonlyArray<UmiaProjectLinkOther>>(
          otherLinks,
          "ens",
          "from ENS · social text records",
        )
      : emptyField<ReadonlyArray<UmiaProjectLinkOther>>([]),
  };

  const project: PrefilledProject = {
    name: field<string>(ensName, "ens", ensSourceLabel("name")),
    description: description
      ? field<string>(description, "ens", ensSourceLabel("description"))
      : emptyField<string>(""),
    pitch: emptyField<string>(""),
    stage: defaultField<UmiaProject["stage"]>("Pre-MVP"),
    links,
  };

  const reportRefBuilt = buildReportRef(evidence, score, reportRef ?? null);
  const reportNote = reportRefToNotes(reportRefBuilt);

  return {
    schema_version: "0.1.0",
    target_command: "umia venture apply",
    submission_track: "community",
    submission_notes: defaultField<string>(reportNote),
    upgrade_siren_report: reportRefBuilt,
    team: {
      members: [seededMember],
    },
    owner_contacts: [seededContact],
    project,
  };
}

// ─── Form → Payload ───

export interface OwnerContactEdits {
  readonly name?: string;
  readonly role?: UmiaRole;
  readonly email?: string;
  readonly telegram?: string;
  readonly twitter?: string;
  readonly discord?: string;
  readonly phone?: string;
  readonly preferred_contact?: UmiaPreferredContact;
}

export interface MemberEdits {
  readonly name?: string;
  readonly role?: UmiaRole;
  readonly bio?: string;
}

export interface BuildPayloadInput {
  readonly form: PrefilledUmiaForm;
  readonly userEdits?: {
    readonly submission_notes?: string;
    readonly owner_contacts?: ReadonlyArray<OwnerContactEdits>;
    readonly members?: ReadonlyArray<MemberEdits>;
    readonly project?: {
      readonly name?: string;
      readonly description?: string;
      readonly pitch?: string;
      readonly stage?: UmiaProject["stage"];
      readonly links?: Partial<{
        readonly website: string;
        readonly github_repositories: ReadonlyArray<string>;
        readonly github_organization: string;
        readonly docs: string;
        readonly demo: string;
        readonly twitter: string;
        readonly telegram: string;
        readonly discord: string;
      }>;
      readonly traction_metrics?: UmiaTractionMetrics;
    };
  };
}

function pickValue<T>(f: PrefilledField<T>, edit: T | undefined): T {
  if (f.locked) return f.value;
  if (edit !== undefined) return edit;
  return f.value;
}

function nonEmptyString(s: string | undefined): string | undefined {
  if (s === undefined) return undefined;
  const trimmed = s.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

export function buildPayloadFromForm(
  input: BuildPayloadInput,
): UmiaVenturePayload {
  const { form, userEdits } = input;
  const edits = userEdits ?? {};

  // ─── owner_contacts[] ───
  const seedContact = form.owner_contacts[0];
  const seedContactEdits = edits.owner_contacts?.[0] ?? {};
  const ownerContactsOut: UmiaOwnerContact[] = [];
  if (seedContact) {
    ownerContactsOut.push(
      compactOwnerContact({
        name: nonEmptyString(pickValue(seedContact.name, seedContactEdits.name)) ?? "",
        role: pickValue(seedContact.role, seedContactEdits.role),
        email: nonEmptyString(pickValue(seedContact.email, seedContactEdits.email)),
        telegram: nonEmptyString(pickValue(seedContact.telegram, seedContactEdits.telegram)),
        twitter: nonEmptyString(pickValue(seedContact.twitter, seedContactEdits.twitter)),
        discord: nonEmptyString(pickValue(seedContact.discord, seedContactEdits.discord)),
        phone: nonEmptyString(pickValue(seedContact.phone, seedContactEdits.phone)),
        wallet_address: nonEmptyString(seedContact.wallet_address.value),
        preferred_contact: pickValue(
          seedContact.preferred_contact,
          seedContactEdits.preferred_contact,
        ),
      }),
    );
  }
  const extraContactEdits = edits.owner_contacts?.slice(1) ?? [];
  for (const c of extraContactEdits) {
    if (!nonEmptyString(c.name)) continue;
    ownerContactsOut.push(
      compactOwnerContact({
        name: c.name!.trim(),
        ...(c.role ? { role: c.role } : {}),
        ...(nonEmptyString(c.email) ? { email: c.email!.trim() } : {}),
        ...(nonEmptyString(c.telegram) ? { telegram: c.telegram!.trim() } : {}),
        ...(nonEmptyString(c.twitter) ? { twitter: c.twitter!.trim() } : {}),
        ...(nonEmptyString(c.discord) ? { discord: c.discord!.trim() } : {}),
        ...(nonEmptyString(c.phone) ? { phone: c.phone!.trim() } : {}),
        ...(c.preferred_contact ? { preferred_contact: c.preferred_contact } : {}),
      }),
    );
  }

  // ─── team.members[] ───
  const seedMember = form.team.members[0];
  const seedMemberEdits = edits.members?.[0] ?? {};
  const membersOut: UmiaTeamMember[] = [];
  if (seedMember) {
    membersOut.push(
      compactMember({
        name: nonEmptyString(pickValue(seedMember.name, seedMemberEdits.name)) ?? "",
        role: pickValue(seedMember.role, seedMemberEdits.role),
        handle: nonEmptyString(seedMember.handle.value),
        wallet_address: nonEmptyString(seedMember.wallet_address.value),
        github: nonEmptyString(seedMember.github.value),
        twitter: nonEmptyString(seedMember.twitter.value),
        bio: nonEmptyString(seedMemberEdits.bio),
      }),
    );
  }
  const extraMemberEdits = edits.members?.slice(1) ?? [];
  for (const m of extraMemberEdits) {
    if (!nonEmptyString(m.name) || !m.role) continue;
    membersOut.push(
      compactMember({
        name: m.name!.trim(),
        role: m.role,
        ...(nonEmptyString(m.bio) ? { bio: m.bio!.trim() } : {}),
      }),
    );
  }

  const team: UmiaTeam = { members: membersOut };

  // ─── project.links ───
  const projectLinks = form.project.links;
  const linksOut: UmiaProjectLinks = compactLinks({
    website: nonEmptyString(
      pickValue(projectLinks.website, edits.project?.links?.website),
    ),
    github_repositories: pickValue(
      projectLinks.github_repositories,
      edits.project?.links?.github_repositories,
    ),
    github_organization: nonEmptyString(
      pickValue(
        projectLinks.github_organization,
        edits.project?.links?.github_organization,
      ),
    ),
    docs: nonEmptyString(
      pickValue(projectLinks.docs, edits.project?.links?.docs),
    ),
    demo: nonEmptyString(
      pickValue(projectLinks.demo, edits.project?.links?.demo),
    ),
    twitter: nonEmptyString(
      pickValue(projectLinks.twitter, edits.project?.links?.twitter),
    ),
    telegram: nonEmptyString(
      pickValue(projectLinks.telegram, edits.project?.links?.telegram),
    ),
    discord: nonEmptyString(
      pickValue(projectLinks.discord, edits.project?.links?.discord),
    ),
    other: projectLinks.other.value,
  });

  const projectOut: UmiaProject = compactProject({
    name: nonEmptyString(
      pickValue(form.project.name, edits.project?.name),
    ) ?? "",
    description:
      nonEmptyString(
        pickValue(form.project.description, edits.project?.description),
      ) ?? "",
    pitch:
      nonEmptyString(pickValue(form.project.pitch, edits.project?.pitch)) ?? "",
    stage: pickValue(form.project.stage, edits.project?.stage),
    links: linksOut,
    traction_metrics: edits.project?.traction_metrics,
  });

  const submissionNotes = nonEmptyString(
    pickValue(form.submission_notes, edits.submission_notes),
  );

  const payload: UmiaVenturePayload = {
    schema_version: "0.1.0",
    target_command: "umia venture apply",
    submission_track: "community",
    ...(submissionNotes ? { submission_notes: submissionNotes } : {}),
    team,
    owner_contacts: ownerContactsOut,
    project: projectOut,
  };
  return payload;
}

function compactOwnerContact(c: {
  name: string;
  role?: UmiaRole;
  email?: string;
  telegram?: string;
  twitter?: string;
  discord?: string;
  phone?: string;
  wallet_address?: string;
  preferred_contact?: UmiaPreferredContact;
}): UmiaOwnerContact {
  const out: { -readonly [K in keyof UmiaOwnerContact]?: UmiaOwnerContact[K] } = {
    name: c.name,
  };
  if (c.role) out.role = c.role;
  if (c.email) out.email = c.email;
  if (c.telegram) out.telegram = c.telegram;
  if (c.twitter) out.twitter = c.twitter;
  if (c.discord) out.discord = c.discord;
  if (c.phone) out.phone = c.phone;
  if (c.wallet_address) out.wallet_address = c.wallet_address;
  if (c.preferred_contact) out.preferred_contact = c.preferred_contact;
  return out as UmiaOwnerContact;
}

function compactMember(m: {
  name: string;
  role: UmiaRole;
  handle?: string;
  wallet_address?: string;
  github?: string;
  twitter?: string;
  bio?: string;
}): UmiaTeamMember {
  const out: { -readonly [K in keyof UmiaTeamMember]?: UmiaTeamMember[K] } = {
    name: m.name,
    role: m.role,
  };
  if (m.handle) out.handle = m.handle;
  if (m.wallet_address) out.wallet_address = m.wallet_address;
  if (m.github) out.github = m.github;
  if (m.twitter) out.twitter = m.twitter;
  if (m.bio) out.bio = m.bio;
  return out as UmiaTeamMember;
}

function compactLinks(l: {
  website?: string;
  github_repositories: ReadonlyArray<string>;
  github_organization?: string;
  docs?: string;
  demo?: string;
  twitter?: string;
  telegram?: string;
  discord?: string;
  other: ReadonlyArray<UmiaProjectLinkOther>;
}): UmiaProjectLinks {
  const out: { -readonly [K in keyof UmiaProjectLinks]?: UmiaProjectLinks[K] } = {
    github_repositories: l.github_repositories,
  };
  if (l.website) out.website = l.website;
  if (l.github_organization) out.github_organization = l.github_organization;
  if (l.docs) out.docs = l.docs;
  if (l.demo) out.demo = l.demo;
  if (l.twitter) out.twitter = l.twitter;
  if (l.telegram) out.telegram = l.telegram;
  if (l.discord) out.discord = l.discord;
  if (l.other.length > 0) out.other = l.other;
  return out as UmiaProjectLinks;
}

function compactProject(p: {
  name: string;
  description: string;
  pitch: string;
  stage: UmiaProject["stage"];
  links: UmiaProjectLinks;
  traction_metrics?: UmiaTractionMetrics;
}): UmiaProject {
  const out: { -readonly [K in keyof UmiaProject]?: UmiaProject[K] } = {
    name: p.name,
    description: p.description,
    pitch: p.pitch,
    stage: p.stage,
    links: p.links,
  };
  if (p.traction_metrics) {
    const t = compactTraction(p.traction_metrics);
    if (Object.keys(t).length > 0) out.traction_metrics = t;
  }
  return out as UmiaProject;
}

function compactTraction(t: UmiaTractionMetrics): UmiaTractionMetrics {
  const out: { -readonly [K in keyof UmiaTractionMetrics]?: UmiaTractionMetrics[K] } = {};
  if (t.monthly_revenue_usd !== undefined) out.monthly_revenue_usd = t.monthly_revenue_usd;
  if (t.monthly_active_users !== undefined) out.monthly_active_users = t.monthly_active_users;
  if (t.github_stars !== undefined) out.github_stars = t.github_stars;
  if (t.github_forks !== undefined) out.github_forks = t.github_forks;
  if (t.other && t.other.length > 0) {
    const cleaned: UmiaTractionMetricOther[] = t.other.filter(
      (x) => typeof x.label === "string" && x.label.length > 0,
    );
    if (cleaned.length > 0) out.other = cleaned;
  }
  return out as UmiaTractionMetrics;
}

// ─── normalisers (idempotent) ───

function normaliseTwitter(raw: string): string {
  if (raw.startsWith("http://") || raw.startsWith("https://")) return raw;
  const handle = raw.replace(/^@/, "");
  return `https://twitter.com/${handle}`;
}

function normaliseTelegram(raw: string): string {
  if (raw.startsWith("http://") || raw.startsWith("https://")) return raw;
  const handle = raw.replace(/^@/, "");
  return `https://t.me/${handle}`;
}

function normaliseDiscord(raw: string): string {
  if (raw.startsWith("http://") || raw.startsWith("https://")) return raw;
  // Bare invite codes get turned into invite URLs; bare server names
  // (rare) flow through unchanged so the user can edit them.
  return `https://discord.gg/${raw.replace(/^@/, "")}`;
}

function normaliseLinkedIn(raw: string): string {
  if (raw.startsWith("http://") || raw.startsWith("https://")) return raw;
  if (raw.startsWith("linkedin.com")) return `https://${raw}`;
  return `https://www.linkedin.com/in/${raw.replace(/^@/, "")}`;
}

function normaliseFarcaster(raw: string): string {
  if (raw.startsWith("http://") || raw.startsWith("https://")) return raw;
  return `https://warpcast.com/${raw.replace(/^@/, "")}`;
}

function normaliseLens(raw: string): string {
  if (raw.startsWith("http://") || raw.startsWith("https://")) return raw;
  if (raw.endsWith(".lens")) return `https://hey.xyz/u/${raw.replace(/\.lens$/, "")}`;
  return `https://hey.xyz/u/${raw.replace(/^@/, "")}`;
}
